Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])

In [7]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
a.transpose()

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = a.mean(axis = 1, dtype = int)

In [14]:
mean_a

array([2, 8])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [33]:
a_new = a.transpose()

In [36]:
mean_a.shape

(2,)

In [37]:
a_new.shape

(5, 2)

In [41]:
a_centered = a_new - mean_a

In [42]:
a_centered

array([[-1, -2],
       [ 0,  0],
       [ 1,  3],
       [ 1,  2],
       [-1, -1]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [46]:
a_centered_1 = a_centered[:, [0]]
a_centered_1

array([[-1],
       [ 0],
       [ 1],
       [ 1],
       [-1]])

In [47]:
a_centered_2 = a_centered[:, [1]]
a_centered_2

array([[-2],
       [ 0],
       [ 3],
       [ 2],
       [-1]])

In [50]:
a_centered_1.shape

(5, 1)

In [51]:
a_centered_2.shape

(5, 1)

In [62]:
b = a_centered_1.transpose()
b

array([[-1,  0,  1,  1, -1]])

In [64]:
c = a_centered_2.transpose()
c

array([[-2,  0,  3,  2, -1]])

In [69]:
a_centered_sp = b.dot(c.transpose())
a_centered_sp

array([[8]])

In [70]:
a_centered.shape[0]

5

In [71]:
result = a_centered_sp / a_centered.shape[0]

In [72]:
result

array([[1.6]])